{% set name = "AdaptiveCpp" %}
{% set version = "24.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/AdaptiveCpp/AdaptiveCpp/archive/v{{ version }}.tar.gz
    sha256: 3bcd94eee41adea3ccc58390498ec9fd30e1548af5330a319be8ce3e034a6a0b
    patches:
      - patches/fallback-missing-functions.patch  # [linux]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('adaptivecpp', max_pin='x.x') }}
  ignore_run_exports:
    - libboost
    - llvm
    - llvm-openmp  # [not win]
  skip: true  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja  # [not win]
    - spirv-tools
  host:
    - clangdev
    - libboost-devel
    - llvm >=14,<19
    - llvm-openmp >=14,<19
  run:
    - llvm >=14,<19

test:
  commands:
    - test -f $PREFIX/include/AdaptiveCpp/sycl/sycl.hpp  # [not win]
    - test -f $PREFIX/lib/cmake/AdaptiveCpp/adaptivecpp-config.cmake  # [not win]
    - test -f $PREFIX/lib/libacpp-common${SHLIB_EXT}  # [not win]
    - acpp-info  # [not win]
    - if not exist %PREFIX%\\Library\\include\\AdaptiveCpp\\SYCL\\sycl.hpp exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\AdaptiveCpp\\adaptivecpp-config.cmake exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\acpp-common.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\acpp-common.dll exit 1  # [win]
    - "acpp-info.exe"  # [win]
  requires:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - clangdev
    - cmake
    - ninja  # [unix]
  files:
    - tests/

about:
  home: https://adaptivecpp.github.io/
  summary: 'The independent, community-driven platform for heterogeneous programming in C++'
  description: |
    AdaptiveCpp is the independent, community-driven modern platform for
    C++-based heterogeneous programming models targeting CPUs and GPUs from all
    major vendors. AdaptiveCpp lets applications adapt themselves to all the
    hardware found in the system. This includes use cases where a single binary
    needs to be able to target all supported hardware, or utilize hardware from
    different vendors simultaneously.
  license: BSD-2-Clause
  license_file: LICENSE
  dev_url: https://github.com/AdaptiveCpp/AdaptiveCpp

extra:
  recipe-maintainers:
    - jeongseok-meta
