{% set name = "adaptivecpp" %}
{% set version = "25.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AdaptiveCpp/AdaptiveCpp/archive/v{{ version }}.tar.gz
  sha256: 7580aa122c28c32c556572226720902053224352760482a842329e4232d95636

build:
  number: 1
  skip: true  # [osx and x86_64]
  skip: true  # [win and cuda_compiler_version == "13.0"]
  string: cpu_llvm{{ llvm_version }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}_llvm{{ llvm_version }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - python
  host:
    - llvm {{ llvm_version }}
    - llvm-dev {{ llvm_version }}
    - clang {{ llvm_version }}
    - clang-tools {{ llvm_version }}
    - libboost-devel
    - libxml2
    - libnuma  # [linux]
    # cuda-compat is needed for libcuda.so.1
    - cuda-compat      # [linux and x86_64]
    - cuda-cudart-dev
    - cuda-driver-dev  # [linux and x86_64]
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - llvm-spirv {{ llvm_version }}.*  # [linux]
    - libopencl-devel
    - spirv-tools  # [linux]
  run:
    - llvm {{ llvm_version }}
    - llvm-dev {{ llvm_version }}
    - clang {{ llvm_version }}
    - clang-tools {{ llvm_version }}
    - libnuma  # [linux]
    - {{ pin_compatible('cuda-version', min_pin='x', max_pin='x') }}  # [cuda_compiler_version != "None"]
    - cuda-cudart-dev  # [cuda_compiler_version != "None"]
    - __cuda  # [cuda_compiler_version != "None"]

test:
  commands:
    - acpp --version
    - test -f $PREFIX/lib/libacpp-rt${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_LIB%\\acpp-rt.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\acpp-rt.dll exit 1  # [win]

about:
  home: https://github.com/AdaptiveCpp/AdaptiveCpp
  license: BSD-2-Clause-Views
  license_family: BSD
  license_file: LICENSE.txt
  summary: AdaptiveCpp is an independent, community-driven modern C++ compiler project for heterogeneous hardware
  description: |
    AdaptiveCpp is an independent, community-driven modern C++ compiler project for heterogeneous hardware.
    It has been developed by Heidelberg University to support their research on parallel programming models.
  doc_url: https://github.com/AdaptiveCpp/AdaptiveCpp
  dev_url: https://github.com/AdaptiveCpp/AdaptiveCpp

extra:
  recipe-maintainers:
    - illuhad
    - jeongseok-meta
